shared/modules/instituicao/controllers/ExemplosController.php
<?php
/**
 * Description of DefaultController
 *
 * @author tiago
 */
class ExemplosController extends InstituicaoController{

    public function actionIndex() {
  		$categorias = ExemplosSearchCategoria::model()->findAll("pai_id IS NULL");
  		$this->render('index', array('categorias' => $categorias));
    }

  public function actionNovaCategoria(){
		$model = new ExemplosSearchCategoria();

		if(isset($_POST['ExemplosSearchCategoria'])){
			$model->attributes = $_POST['ExemplosSearchCategoria'];
			if($model->save()){
				Yii::app()->user->setFlash(self::SUCS_FLASH, 'Categoria criada.');
				$this->redirect($this->createUrl('exemplos/index'));
			}
		}

		$this->render('novaCat', array(
			'model' => $model,
		));
	}

	public function actionEditCategoria($id){
		$model = ExemplosSearchCategoria::model()->findByPk($id);
		if(isset($_POST['ExemplosSearchCategoria'])){
			$model->attributes = $_POST['ExemplosSearchCategoria'];
			if($model->save()){
				Yii::app()->user->setFlash(self::SUCS_FLASH, 'Categoria criada.');
				$this->redirect($this->createUrl('exemplos/index'));
			}
		}

		$this->render('novaCat', array(
			'model' => $model,
		));
	}

	public function actionEditarOrdem($id){
		$model = ExemplosSearchCategoria::model()->findByPk($id);
		if(isset($_POST['ordem']) && is_array($_POST['ordem'])){
		    foreach ($_POST['ordem'] as $e => $o) {
          ExemplosSearch::model()->updateByPk((int) $e,array(
            'ordem' => $o,
          ));
		    }
		}

		$this->render('ordem', array(
			'model' => $model,
		));
	}

    public function actionExcCategoria($id){
		$model = ExemplosSearchCategoria::model()->findByPk($id);
    if(count($model->filhas) > 0){
      foreach ($model->filhas as $f) {
        $f->pai_id = null;
        $f->update(array('pai_id'));
      }
    }

		if($model->delete()){
			Yii::app()->user->setFlash(self::SUCS_FLASH, 'Categoria excluído.');
		} else {
			Yii::app()->user->setFlash(self::ERRO_FLASH, 'Falha ao categoria.');
		}
		$this->redirect($this->createUrl('exemplos/index'));
	}

    public function actionNovoExemplo(){
		$model = new ExemplosSearch();
		$categorias = ExemplosSearchCategoria::model()->findAll();
		if(isset($_POST['ExemplosSearch'])){
			$model->attributes = $_POST['ExemplosSearch'];
			if($model->save()){
				Yii::app()->user->setFlash(self::SUCS_FLASH, 'Exemplo criado.');
				$this->redirect($this->createUrl('exemplos/index'));
			}
		}

		$this->render('novoEx', array(
			'model' => $model,
			'categorias' => CHtml::listData($categorias, 'id', 'nome'),
		));
	}


    public function actionEditEx($id){
		$model = ExemplosSearch::model()->findByPk($id);
		$categorias = ExemplosSearchCategoria::model()->findAll();
		if(isset($_POST['ExemplosSearch'])){
			$model->attributes = $_POST['ExemplosSearch'];
			if($model->save()){
				Yii::app()->user->setFlash(self::SUCS_FLASH, 'Exemplo criado.');
				$this->redirect($this->createUrl('exemplos/index'));
			}
		}

		$this->render('novoEx', array(
			'model' => $model,
			'categorias' => CHtml::listData($categorias, 'id', 'nome'),
		));
	}


    public function actionExcEx($id){
		$model = ExemplosSearch::model()->findByPk($id);
		if($model->delete()){
			Yii::app()->user->setFlash(self::SUCS_FLASH, 'Exemplo excluído.');
		} else {
			Yii::app()->user->setFlash(self::ERRO_FLASH, 'Falha ao excluir.');
		}
		$this->redirect($this->createUrl('exemplos/index'));
	}

  public function actionPublicar($id){
    if($this->updateExemploEstado($id,1)){
      Yii::app()->user->setFlash(self::SUCS_FLASH,'Publicado.');
    } else {
      Yii::app()->user->setFlash(self::ERRO_FLASH,'Erro ao publicar.');
    }
    $this->redirect($this->createUrl('exemplos/index'));
  }

  public function actionDespublicar($id){
    if($this->updateExemploEstado($id,0)){
      Yii::app()->user->setFlash(self::SUCS_FLASH,'Despublicado.');
    } else {
      Yii::app()->user->setFlash(self::ERRO_FLASH,'Erro ao despublicar.');
    }
    $this->redirect($this->createUrl('exemplos/index'));
  }

  public function actionPublicarTodos($catId){
    $cat = ExemplosSearchCategoria::model()->findByPk($catId);
    foreach ($cat->todosExemplos as $e) {
      $this->updateExemploEstado($e->id,1);
    }
    Yii::app()->user->setFlash(self::SUCS_FLASH,'Categoria publicada.');
    $this->redirect($this->createUrl('exemplos/index'));
  }
  public function actionDespublicarTodos($catId){
    $cat = ExemplosSearchCategoria::model()->findByPk($catId);
    foreach ($cat->todosExemplos as $e) {
      $this->updateExemploEstado($e->id,0);
    }
    Yii::app()->user->setFlash(self::SUCS_FLASH,'Categoria despublicada.');
    $this->redirect($this->createUrl('exemplos/index'));
  }

  private function updateExemploEstado($id,$estado){
    $exemplo = ExemplosSearch::model()->findByPk($id);
    $exemplo->publicado = $estado;
    return $exemplo->update(array('publicado'));
  }


}

shared/modules/instituicao/views/exemplos/_carForm.php
<?php
$form = $this->beginWidget('CActiveForm', array(
    'id' => 'teclado-form-categoria',
    'enableAjaxValidation' => false,
        ));
?>
<?php
if (!$model->isNewRecord) {
    echo '<p class="textRight">';
    echo CHtml::link('Excluir', $this->createUrl('teclado/excluirCategoria', array('id' => $model->id)), array(
        'confirm' => 'Todas as teclas desta categoria também serão excluídas. Confirma exclusão de categoria?',
    ));
    echo '</p>';
}
?>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'nome'); ?>
    </div>
    <div class="column medium-10">
        <?php echo $form->textField($model, 'nome', array('class' => 'medium-4')); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo $form->error($model, 'nome'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'pai_id'); ?>
    </div>
    <div class="column medium-10">
        <?php $pais = ExemplosSearchCategoria::model()->findAll(); ?>
        <?php echo $form->dropDownList($model, 'pai_id', CHtml::listData($pais,'id','nome')
        , array('class' => 'medium-4','prompt'=>false)); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo $form->error($model, 'pai_id'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Criar' : 'Atualizar', array('class' => 'btn btn-success')); ?>
    </div>
</div>

<?php $this->endWidget(); ?>

shared/modules/instituicao/views/exemplos/_formEx.php
<?php

$form = $this->beginWidget('CActiveForm', array(
    'id' => 'comandos-teclado-_form-form',
    'enableAjaxValidation' => false,
        ));

?>

<?php
if (!$model->isNewRecord) {
    echo '<p class="textRight">';
    echo CHtml::link('Excluir', $this->createUrl('teclado/excluirTecla', array('id' => $model->id)), array(
        'confirm' => 'Confirma exclusão de tecla?',
    ));
    echo '</p>';
}
?>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'categoria_id'); ?>
    </div>
    <div class="column medium-10">
        <?php echo $form->dropDownList($model, 'categoria_id', array(null=>null) + $categorias, array('class' => 'medium-4')); ?>
        <?php //echo CHtml::link('Nova categoria', ShCode::getModUrl('instituicao', 'teclado', 'novaCategoria', array('id' => $id, 'rt' => ShCode::geraLinkRetorno(array('id'))))) ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'latex'); ?>
    </div>
    <div class="column medium-10">
        <?php echo $form->textField($model, 'latex', array('class' => 'medium-4')); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo $form->error($model, 'latex'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'valor'); ?>
    </div>
    <div class="column medium-10">
        <?php echo $form->textField($model, 'valor', array('class' => 'medium-4')); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo $form->error($model, 'valor'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-2">
        <?php echo $form->labelEx($model, 'layout'); ?>
    </div>
    <div class="column medium-10">
        <?php echo $form->dropDownList($model, 'layout', ExemplosSearch::layoutTipos(), array('class' => 'medium-4')); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo $form->error($model, 'layout'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="column medium-12">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Criar' : 'Atualizar', array('class' => 'btn btn-success')); ?>
    </div>
</div>

<?php $this->endWidget(); ?>

shared/modules/instituicao/views/exemplos/index.php
<?php
$this->menuContexto = array(
	ShCode::makeItem('Nova categoria', $this->createUrl('exemplos/NovaCategoria')),
	ShCode::makeItem('Novo exemplos', $this->createUrl('exemplos/NovoExemplo')),
);
$this->renderPartial('linha',array('categorias'=>$categorias));

shared/modules/instituicao/views/exemplos/linha.php
<div style='padding-left:40px;'>
  <?php
  foreach($categorias as $c) {
    echo '<table class="table">';
    echo '<tr><td colspan="3" class="">';
    echo "<h3 style='display:inline-block;'>{$c->nome}</h3>   ";
    echo CHtml::link('Editar', $this->createUrl('exemplos/EditCategoria', array('id' => $c->id)), array('class' => 'btn btn-xs btn-info'));
    echo CHtml::link('Ordem', $this->createUrl('exemplos/EditarOrdem', array('id' => $c->id)), array('class' => 'btn btn-xs btn-default'));
    echo CHtml::link('x', $this->createUrl('exemplos/excCategoria', array('id' => $c->id)), array('class' => 'btn btn-xs btn-red', 'confirm' => 'Certeza?'));
    echo '<br><br>';
    echo CHtml::link('Despublicar todos', $this->createUrl('exemplos/despublicarTodos', array('catId' => $c->id)), array('class' => 'btn btn-xs btn-primary'));
    echo CHtml::link('Publicar todos', $this->createUrl('exemplos/publicarTodos', array('catId' => $c->id)), array('class' => 'btn btn-xs btn-success'));
    echo '<br><br></td></tr>';

    foreach($c->todosExemplos as $e){

      echo '<tr>';
      echo "<td>$ {$e->latex} $</td>";
      echo "<td style='font-family:monospace; color: #333;'>{$e->valor}</td>";
      echo '<td>';
      echo CHtml::link('Editar', $this->createUrl('exemplos/EditEx', array('id' => $e->id)), array('class' => 'btn btn-xs btn-info'));

      if($e->publicado == 1){
         echo CHtml::link('Despublicar', $this->createUrl('exemplos/despublicar', array('id' => $e->id)), array('class' => 'btn btn-xs btn-primary'));
      } else {
         echo CHtml::link('Publicar', $this->createUrl('exemplos/publicar', array('id' => $e->id)), array('class' => 'btn btn-xs btn-success'));
      }

      echo CHtml::link('x', $this->createUrl('exemplos/excEx', array('id' => $e->id)), array('class' => 'btn btn-xs', 'confirm' => 'Certeza?'));
      echo '</td>';
      echo '</tr>';

    }

    echo '</table>';

    $this->renderPartial('linha',array('categorias'=>$c->filhas));
  }
  ?>
</div>

shared/modules/instituicao/views/exemplos/novaCat.php
<?php

$this->renderPartial('_carForm', array('model' => $model));

shared/modules/instituicao/views/exemplos/novoEx.php
<?php

$this->renderPartial('_formEx', array('model' => $model, 'categorias' => $categorias));

shared/modules/instituicao/views/exemplos/ordem.php
<?php
$this->menuContexto = array(
	ShCode::makeItem('Finalizar edição de ordem', $this->createUrl('exemplos/index')),
);
$this->pageTitle = 'Ordem exemplos categoria ' . $model->nome;
?>
<form method='POST' action="<?=$this->createUrl('exemplos/editarOrdem',array('id'=>$model->id))?>">
  <?php foreach ($model->todosExemplos as $e): ?>
    <input name='ordem[<?=$e->id?>]' type='number' value='<?=$e->ordem?>' style='width:60px;' min=0 />&nbsp;&nbsp;&nbsp;
    <span title="<?=$e->valor;?>">$<?=$e->latex?>$</span><br>
  <?php endforeach; ?>
  <button type='submit'>Salvar</button>
</form>