shared/modules/mensagem/models/ArqArquivo.php
<?php

/**
 * This is the model class for table "arquivo".
 *
 * The followings are the available columns in table 'arquivo':
 * @property integer $id
 * @property string $alias
 * @property string $nome
 * @property string $user_id
 * @property integer $publicado
 *
 * The followings are the available model relations:
 * @property User $autor
 */
class ArqArquivo extends CActiveRecord {

    public $file;

    public function tableName() {
        return 'arquivo';
    }

    public static function getTableName() {
        return 'arquivo';
    }

    public function rules() {
        return array(
            array('file', 'file', 'types' => 'jpg, gif, png, pdf, doc, docx, csv'),
            array('nome, user_id', 'required'),
            array('publicado', 'numerical', 'integerOnly' => true),
            array('alias', 'length', 'max' => 256),
            array('nome', 'length', 'max' => 512),
            array('user_id', 'length', 'max' => 100),
            array('id, alias, nome, user_id, publicado', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'autor' => array(self::BELONGS_TO, 'User', 'user_id'),
        );
    }

    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'alias' => 'Alias',
            'nome' => 'Nome',
            'user_id' => 'Autor',
            'publicado' => 'Publicado',
        );
    }

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function generateAlias($uploadName) {
        $extension = pathinfo($uploadName, PATHINFO_EXTENSION);
        return md5($uploadName . microtime(true)) . '.' . $extension;
    }

    public function scopes() {
        return array(
            'doAutor' => array(
                'condition' => "user_id = '" . Yii::app()->user->id . "'"
            ),
        );
    }

}

shared/modules/mensagem/controllers/DefaultController.php
<?php

/**
 * Description of DefaultController
 *
 * @author tiago
 */
class DefaultController extends MensagemController {

    public function actionIndex() {
        $this->redirect($this->createUrl('ler/listar'));
    }
    
}

shared/modules/mensagem/controllers/EnviarController.php
<?php

/**
 * Description of EnviarController
 *
 * @author tiago
 */
class EnviarController extends MensagemController {

    public function actionEscrever() {
        if (isset($_POST['destinos']) && isset($_POST['mensagem'])) {
            foreach ($_POST['destinos'] as $d) {
                // TODO: validar se destino está entre os usuários "amigos"
                if (ShMsg::enviar($d, $_POST['mensagem'])) {
                    Yii::app()->user->setFlash(self::SUCS_FLASH, 'Mensagem enviada!');
                } else {
                    Yii::app()->user->setFlash(self::ERRO_FLASH, 'Mensagem não enviada!');
                }
            }
            if (isset($_POST['replicaEmEmail'])) {
                ShEmail::send($_POST['destinos'], 'Mensagem', $this->orgID, 'noreply@noreply.com', $_POST['mensagem']);
            }
        }

        $this->render('escrever', array(
            'users' => $this->getUsers(),
        ));
    }

    public function actionReply($id) {
        $mensagem = Mensagem::model()->queRecebi()->findByPk((int) $id);
        if (!is_null($mensagem)) {
            $this->render('escrever', array(
                'users' => $this->getUsers(),
                'options' => array($mensagem->de => array('selected' => true)),
                'body' => $this->renderPartial('_bodyReply', array('msg' => $mensagem), true),
            ));
        } else {
            Yii::app()->user->setFlash(self::ERRO_FLASH, 'Mensagem não encontrada.');
            $this->redirect($this->createUrl('ler/listar'));
        }
    }

    public function getUsers() {
        // TODO: não buscar todos! somente aqueles relacionados ao usuário
        return CHtml::listData(User::model()->findAll(), 'id', 'perfil.nome');
    }

}

shared/modules/mensagem/controllers/LerController.php
<?php

/**
 * Description of VerController
 *
 * @author tiago
 */
class LerController extends MensagemController {

    /**
     * Mostra mensagem e atualiza para lida
     * @param type $id
     */
    public function actionIndex($id) {
        $msg = $this->getMensagemRecebida($id);
        if (!$msg->lida) {
            $msg->setAsLida();
        }
        $this->render('ler', array(
            'msg' => $msg,
        ));
    }

    /**
     * Mostra mensagem e atualiza para lida
     * @param type $id
     */
    public function actionEnviada($id) {
        $msg = $this->getMensagemEnviei($id);
        $this->render('ler', array(
            'msg' => $msg,
        ));
    }

    /**
     * Lista das as mensagens que o autor recebeu
     */
    public function actionListar() {
        $msgs = Mensagem::model()->queRecebi()->findAll(array('order' => 'dataEnvio DESC'));
        $this->render('recebidas', array(
            'msgs' => $msgs,
        ));
    }

    /**
     * Lista das as mensagens que o autor envio
     */
    public function actionEnviadas() {
        $msgs = Mensagem::model()->queEnvie()->findAll(array('order' => 'dataEnvio DESC'));
        $this->render('enviadas', array(
            'msgs' => $msgs,
        ));
    }

    public function actionExcluir($id) {
        $msg = Mensagem::model()->queRecebi()->findByPk((int) $id);
        if (!is_null($msg)) {
            if ($msg->setAsDelete()) {
                Yii::app()->user->setFlash(self::SUCS_FLASH, 'Mensagem movida para a lixeira.');
            } else {
                Yii::app()->user->setFlash(self::ERRO_FLASH, 'Não foi possível excluir mensagem.');
            }
        } else {
            Yii::app()->user->setFlash(self::ERRO_FLASH, 'Mensagem não enconttrada na caixa de entrada.');
        }
        $this->redirect($this->createUrl('ler/listar'));
    }

    /**
     * Lista das as mensagens que o autor envio
     */
    public function actionExcluidas() {
        $msgs = Mensagem::model()->excluidas()->findAll(array('order' => 'dataEnvio DESC'));
        $this->render('excluidas', array(
            'msgs' => $msgs,
        ));
    }

//    /**
//     * Lista das as mensagens que o usuario salvou
//     */
//    public function actionRascunhos() {
//        $this->render('rascunhos', array(
//        ));
//    }
}

shared/modules/mensagem/views/ler/enviadas.php
<?php $this->beginContent('mensagem.views.layouts.base'); ?>
<div class="box-header with-border">
    <h3 class="box-title">Enviadas</h3>
    <div class="box-tools pull-right">
        <div class="has-feedback">
            <input type="text" class="form-control input-sm" placeholder="Buscar mensagem"/>
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
        </div>
    </div><!-- /.box-tools -->
</div><!-- /.box-header -->
<div class="box-body no-padding">
    <div class="mailbox-controls">
        <!-- Check all button -->
    <!--        <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
            </div> /.btn-group -->
        <?= CHtml::link("<i class='fa fa-refresh'></i>", $this->createUrl('ler/enviadas'), array('class' => 'btn btn-default btn-sm')); ?>
        <div class="pull-right">
            1-50/200
            <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
            </div><!-- /.btn-group -->
        </div><!-- /.pull-right -->
        <br>
        <br>
    </div>
    <div class="table-responsive mailbox-messages">
        <table class="table table-hover table-striped">
            <tbody>
                <?php foreach ($msgs as $m): ?>
                    <tr>
                        <td class="mailbox-attachment">
                            <?php
                            echo "<a href='#'><i class='fa fa-circle-o text-yellow '></i></a> ";
                            if ($m->entregue) {
                                echo "<a href='#'><i title='" . ShMsg::tempoAteAgora($m->dataEntrega) . "' class='fa fa-circle-o text-blue'></i></a> ";
                                if ($m->lida) {
                                    echo "<a href='#'><i title='" . ShMsg::tempoAteAgora($m->dataLeitura) . "' class='fa fa-circle-o text-green'></i></a>";
                                }
                            }
                            ?>
                        </td>
                        <td class="mailbox-name">
                            <?php if (isset($m->destino->perfil)): ?>
                                <a href="<?= ShCode::getModUrl('mensagem', 'ler', 'enviada', array('id' => $m->id)); ?>"><?= $m->destino->perfil->nome; ?></a>
                            <?php endif; ?>
                        </td>
                        <?php $msg = strip_tags($m->mensagem); ?>
                        <td class="mailbox-subject"><?= substr($msg, 0, 60) . (strlen($msg) > 60 ? '...' : '') ?></td>
                        <td class="mailbox-date"><div class="right"><?= ShMsg::tempoAteAgora($m->dataEnvio); ?></div></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table><!-- /.table -->
    </div><!-- /.mail-box-messages -->
</div><!-- /.box-body -->
<div class="box-footer no-padding">
    <div class="mailbox-controls">
        <br>
        <div class="pull-right">
            1-50/200
            <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
            </div><!-- /.btn-group -->
        </div><!-- /.pull-right -->
        <br>
        <br>
    </div>
</div>
<?php $this->endContent(); ?>

shared/modules/mensagem/views/ler/excluidas.php
<?php $this->beginContent('mensagem.views.layouts.base'); ?>
<div class="box-header with-border">
    <h3 class="box-title">Excluídas</h3>
    <div class="box-tools pull-right">
        <div class="has-feedback">
            <input type="text" class="form-control input-sm" placeholder="Buscar mensagem"/>
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
        </div>
    </div><!-- /.box-tools -->
</div><!-- /.box-header -->
<div class="box-body no-padding">
    <div class="mailbox-controls">
        <br><br>
    </div>
    <div class="table-responsive mailbox-messages">
        <table class="table table-hover table-striped">
            <tbody>
                <?php foreach ($msgs as $m): ?>
                    <tr>
                        <td class="mailbox-attachment">
                            
                        </td>
                        <td class="mailbox-name">
                            <?php if (isset($m->destino->perfil)): ?>
                                <a href="<?= ShCode::getModUrl('mensagem', 'ler', 'enviada', array('id' => $m->id)); ?>"><?= $m->destino->perfil->nome; ?></a>
                            <?php endif; ?>
                        </td>
                        <?php $msg = strip_tags($m->mensagem); ?>
                        <td class="mailbox-subject"><?= substr($msg, 0, 60) . (strlen($msg) > 60 ? '...' : '') ?></td>
                        <td class="mailbox-date"><div class="right"><?= ShMsg::tempoAteAgora($m->dataEnvio); ?></div></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table><!-- /.table -->
    </div><!-- /.mail-box-messages -->
</div><!-- /.box-body -->
<?php $this->endContent(); ?>

shared/modules/mensagem/views/ler/ler.php
<?php $this->beginContent('mensagem.views.layouts.base'); ?>
<div class="box-header with-border">
    <h3 class="box-title">Mensagem</h3>
    <div class="box-tools pull-right">
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Previous"><i class="fa fa-chevron-left"></i></a>
        <a href="#" class="btn btn-box-tool" data-toggle="tooltip" title="Next"><i class="fa fa-chevron-right"></i></a>
    </div>
</div><!-- /.box-header -->
<div class="box-body no-padding">
    <div class="mailbox-read-info">
        <span class="mailbox-read-time pull-right">Enviada em: <?= date("d/m/Y H:i:s", $msg->dataEnvio); ?> (<?= ShMsg::tempoAteAgora($msg->dataEnvio); ?>)</span>
        <?php if ($msg->de == Yii::app()->user->id): ?>
            <h5>Para <b><?= $msg->destino->perfil->nome; ?></b>
                <!--para <?//= $msg->destino->perfil->nome; ?>-->
            </h5>
        <?php else: ?>
            <h5>De <b><?= $msg->origem->perfil->nome; ?></b>
                <!--para <?//= $msg->destino->perfil->nome; ?>-->
            </h5>
        <?php endif; ?>
    </div><!-- /.mailbox-read-info -->
    <hr>
    <div class="mailbox-read-message">
        <?= $msg->mensagem; ?>
    </div><!-- /.mailbox-read-message -->
</div><!-- /.box-body -->
<div class="box-footer">
    <?php if ($msg->de != Yii::app()->user->id): ?>
        <div class="pull-right">
            <?= CHtml::link("<i class='fa fa-reply'></i> Reply", $this->createUrl('enviar/reply', array('id' => $msg->id)), array('class' => 'btn btn-default')); ?>
            <!--<button class="btn btn-default"><i class="fa fa-share"></i> Forward</button>-->
        </div>
        <?= CHtml::link('<i class="fa fa-trash-o"></i> Delete', $this->createUrl('ler/excluir', array('id' => $msg->id)), array('class' => 'btn btn-default')); ?>
        <!--<button class="btn btn-default"><i class="fa fa-print"></i> Print</button>-->
    <?php endif; ?>
</div><!-- /.box-footer -->
<?php $this->endContent(); ?>

shared/modules/mensagem/views/ler/rascunhos.php
<?php $this->beginContent('mensagem.views.layouts.base'); ?>
<div class="box-header with-border">
    <h3 class="box-title">Em breve</h3>
</div><!-- /.box-header -->
<div class="box-body no-padding">
    Recurso em desenvolvimento.
</div><!-- /.box-body -->
<?php $this->endContent(); ?>

shared/modules/mensagem/views/ler/recebidas.php
<?php $this->beginContent('mensagem.views.layouts.base'); ?>
<div class="box-header with-border">
    <h3 class="box-title">Recebidas</h3>
    <div class="box-tools pull-right">
        <div class="has-feedback">
            <input type="text" class="form-control input-sm" placeholder="Buscar mensagem"/>
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
        </div>
    </div><!-- /.box-tools -->
</div><!-- /.box-header -->
<div class="box-body no-padding">
    <div class="mailbox-controls">
        <!-- Check all button -->
<!--        <div class="btn-group">
            <button class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
            <button class="btn btn-default btn-sm"><i class="fa fa-reply"></i></button>
            <button class="btn btn-default btn-sm"><i class="fa fa-share"></i></button>
        </div> /.btn-group -->
        <?= CHtml::link("<i class='fa fa-refresh'></i>", $this->createUrl('ler/listar'), array('class' => 'btn btn-default btn-sm')); ?>
        <div class="pull-right">
            1-50/200
            <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
            </div><!-- /.btn-group -->
        </div><!-- /.pull-right -->
        <br><br>
    </div>
    <div class="table-responsive mailbox-messages">
        <table class="table table-hover table-striped">
            <tbody>
                <?php foreach ($msgs as $m): ?>
                    <tr>
                        <td>
                            <?php if (!$m->lida): ?>
                                <a href="#"><i class="fa fa-circle-o text-blue"></i></a>
                            <?php endif; ?>
                        </td>
                        <td class="mailbox-name"><a href="<?= ShCode::getModUrl('mensagem', 'ler', 'index', array('id' => $m->id)); ?>"><?= $m->origem->perfil->nome; ?></a></td>
                        <?php $msg = strip_tags($m->mensagem); ?>
                        <td class="mailbox-subject"><?= substr($msg, 0, 60) . (strlen($msg) > 60 ? '...' : '') ?></td>
                        <td class="mailbox-date"><div class="right"><?= ShMsg::tempoAteAgora($m->dataEnvio); ?></div></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table><!-- /.table -->
    </div><!-- /.mail-box-messages -->
</div><!-- /.box-body -->
<div class="box-footer no-padding">
    <div class="mailbox-controls">
        <br>
        <div class="pull-right">
            1-50/200
            <div class="btn-group">
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></button>
                <button class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></button>
            </div><!-- /.btn-group -->
        </div><!-- /.pull-right -->
        <br><br>
    </div>
</div>
<?php $this->endContent(); ?>