shared/modules/questionarios/controllers/QuestionarioController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of QuestionarioController
 *
 * @author tiago
 */
class QuestionarioController extends QuestionariosController {

    /**
     * Lista questionários do autor
     */
    public function actionListar() {
        $questionarios = QstQuestionario::model()->doAutor()->findAll();
        $this->render('listar', array(
            'questionarios' => $questionarios,
        ));
    }

    public function actionImprimir($id) {
        $this->layout = 'questionarios.views.layouts.imprimir';
        $questionario = $this->getQuestionario($id);
        $this->render('imprimir', array(
            'questionario' => $questionario,
        ));
    }

    /**
     * Criação de novo questionário
     */
    public function actionNovo() {
        $model = new QstQuestionario();

        if (isset($_POST['QstQuestionario'])) {
            $model->attributes = $_POST['QstQuestionario'];
            $model->user_id = Yii::app()->user->id;
            if ($model->save()) {
                $this->redirect($this->createUrl('questionario/editar', array('id' => $model->id)));
            }
        }

        $this->render('novo', array(
            'model' => $model,
        ));
    }

    /**
     * Visualizaxao de questionário
     * @param type $id
     */
    public function actionEditar($id) {
        $questionario = $this->getQuestionario($id);
        $questoes = QstQuestao::model()->doAutor()->findAll();
        $this->render('editar', array(
            'questionario' => $questionario,
            'questoes' => $questoes,
        ));
    }

    /**
     * Conecta uma questão ao questionário
     */
    public function actionConectarQuestao($id, $contID) {
        $questionario = $this->getQuestionario($id);
        $questao = $this->getQuestao($contID);
        if ($questionario->criaConexao($questao)) {
            Yii::app()->user->setFlash(self::SUCS_FLASH, 'Questão incluída.');
        } else {
            Yii::app()->user->setFlash(self::ERRO_FLASH, 'Questão não foi incluída.');
        }
        $this->redirect($this->createUrl('questionario/editar', array('id' => $questionario->id)));
    }

    /**
     * Conecta uma questão ao questionário
     */
    public function actionDesconectarQuestao($id, $contID) {
        $questionario = $this->getQuestionario($id);
        $questao = $this->getQuestao($contID);
        if ($questionario->desfazConexao($questao)) {
            echo '1';
        } else {
            echo ('Questão não foi removida.');
        }
    }

    /**
     * Configuração do formulário
     * @param type $id
     */
    public function actionConfigurar($id) {
        $questionario = $this->getQuestionario($id);

        if (isset($_POST['QstQuestionario'])) {
            $questionario->nome = $_POST['QstQuestionario']['nome'];
            $questionario->publicado = $_POST['QstQuestionario']['publicado'];
            if ($questionario->save()) {
                ShCode::setFlashSucesso('Questionário atualizado.');
                $this->redirect($this->createUrl('questionario/editar', array('id' => $questionario->id)));
            }
        }

        $this->render('configurar', array(
            'model' => $questionario,
        ));
    }

    public function actionExcluir($id){
      $questionario = $this->getQuestionario($id);
      CursoAulaQuestionario::model()->deleteAll(array(
        'condition' => "questionario_id = {$questionario->id} AND user_id = " . Yii::app()->user->id,
      ));
      QuestaoResposta::model()->deleteAll(array(
        'condition' => "questionario_id = {$questionario->id}",
      ));
      QuestionarioQuestao::model()->deleteAll(array(
        'condition' => "questionario_id = {$questionario->id} AND user_id = " . Yii::app()->user->id,
      ));
      if($questionario->delete()){
        Yii::app()->user->setFlash(self::SUCS_FLASH,'Questionário excluído.');
      } else {
        Yii::app()->user->setFlash(self::ERRO_FLASH,'Falha ao excluir questionário.');
      }
      $this->redirect($this->createUrl('/meuEspaco/questionarios/questionario/listar'));
    }

}

shared/modules/questionarios/views/questionario/_form.php
<?php
$form = $this->beginWidget('CActiveForm', array(
    'id' => 'novo-questionario',
    'enableAjaxValidation' => false,
        ));
?>
<div class="sh-row">
    <div class="columns medium-2">
        <?php echo $form->labelEx($model, 'nome'); ?>
    </div>
    <div class="columns medium-4">
        <?php echo $form->textField($model, 'nome'); ?>
    </div>
    <div class="columns medium-6">
        <?php echo $form->error($model, 'nome'); ?>
    </div>
</div>
<div class="sh-row">
    <div class="columns medium-2">
        <?php echo $form->labelEx($model, 'publicado'); ?>
    </div>
    <div class="columns medium-4">
        <?php echo $form->dropDownList($model, 'publicado',array(
          0 => 'Não',
          1 => 'Sim',
        )); ?>
    </div>
    <div class="columns medium-6">
        <?php echo $form->error($model, 'publicado'); ?>
    </div>
</div>
<br>
<div class="sh-row">
    <div class="columns medium-12">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Criar' : 'Atualizar', array('class' => 'btn btn-success')); ?>
    </div>
</div>
<?php $this->endWidget(); ?>

shared/modules/questionarios/views/questionario/_listaQuestoes.php
<?php echo CHtml::textField("filtroTopicos", "", array('placeholder' => 'Localizar questão...', 'id' => 's', 'class' => 'column medium-4')); ?>
<br><br>
<?php $questoesIDS = CHtml::listData($questionario->questoes, 'id', 'id'); ?>
<?php if (count($questoes) > 0): ?>
    <ul class="medium-block-grid-4">
        <?php foreach ($questoes as $qst): ?>
            <li>
                <div class="box">
                    <div class="box-header">
                        <?php
                        if (in_array($qst->id, $questoesIDS)) {
                            echo CHtml::link('Remover', $this->createUrl('questionario/DesconectarQuestao', array(
                                        'id' => $questionario->id,
                                        'contID' => $qst->id,
                                    )), array('class' => 'btn btn-xs btn-danger'));
                        } else {
                            echo CHtml::link('Incluir', $this->createUrl('questionario/ConectarQuestao', array(
                                        'id' => $questionario->id,
                                        'contID' => $qst->id,
                                    )), array('class' => 'btn btn-xs btn-info'));
                        }
                        ?>
                    </div>
                    <div class="box-body s">
                        <?= $qst->enunciado; ?>
                    </div>
                </div>

            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <h4 class='hint'>Nenhum questão criada.</h4>    
<?php endif; ?>

<script>
    $('#s').keyup(function() {
        $('.s').each(function() {
            var n = $(this).text().toLowerCase();
            if (n.indexOf($('#s').val().toLowerCase()) === -1) {
                $(this).parent().parent().fadeOut();
            } else {
                $(this).parent().parent().fadeIn();
            }
        });
    });
</script>

shared/modules/questionarios/views/questionario/_questao.php
<div class="box" id="qst-<?= $data->id ?>">
    <div class="box-header">
        <div class="pull-right">
            <?php
            if ($add) {
                echo CHtml::link('Incluir', $this->createUrl('questionario/ConectarQuestao', array(
                            'id' => $id,
                            'contID' => $data->id,
                        )), array('class' => 'btn btn-xs btn-info'));
            } else {
                echo CHtml::ajaxLink('Remover', $this->createUrl('questionario/DesconectarQuestao', array(
                            'id' => $id,
                            'contID' => $data->id,
                        )), array(
                    'beforeSend' => 'js: function() { $("#qst-' . $data->id . '").append("<div class=\'overlay\'><i class=\'fa fa-refresh fa-spin\'></i></div>"); }',
                    'success' => 'js: function(html) { '
                    . 'if(html === "1"){'
                    . '$("#qst-' . $data->id . '").slideUp().remove();'
                    . '} else {'
                    . 'alert(html);'
                    . '$("#qst-' . $data->id . ' .overlay").remove();'
                    . '  }'
                    . '} ',
                        ), array(
                    'class' => 'btn btn-xs btn-danger',
                    'id' => 'remover' . $data->id));
            }
            ?>
        </div>
        <br>
    </div>
    <div class="box-body <?= $add ? 's' : ''; ?>" style="display: block; height: 100px; background: transparent; overflow: hidden; overflow-y: auto;" class="box-body">
        <?php echo $data->enunciado; ?>
    </div>
</div>

shared/modules/questionarios/views/questionario/configurar.php
<?php
$this->pageTitle = 'Editar questionário ' . $model->nome;
$this->menuContexto = array(
    ShCode::makeItem('Cancelar', $this->createUrl('questionario/editar', array('id' => $model->id))),
);
?>
<div class="sh-row">
    <div class="columns medium-12">
        <p class="hint">
            Configurações de tempo de resolução, quantidade de tentativas, etc, 
            serão definidas quando o questionário for utilizado em curso. Você pode usar o mesmo questionário em vários cursos.
            <br>
            <br>
        </p>
        <?php $this->renderPartial('_form', array('model' => $model)); ?>
    </div>
</div>

shared/modules/questionarios/views/questionario/editar.php
<?php
$this->pageTitle = $questionario->nome;
$this->menuContexto = array(
    ShCode::makeItem('Voltar', $this->createUrl('questionario/listar')),
    ShCode::makeItem('Editar questionário', $this->createUrl('questionario/configurar', array('id' => $questionario->id))),
    ShCode::makeItem('Excluir questionário', $this->createUrl('questionario/excluir', array('id' => $questionario->id))),
);
?>
<h4>Questões no questionário.</h4>
<ul class="medium-block-grid-4 small-block-grid-1">
    <?php
    $noQuestionario = array();
    foreach ($questionario->questoes as $questao) {
        $noQuestionario[] = $questao->id;
        echo '<li>' . $this->renderPartial('_questao', array(
            'id' => $questionario->id,
            'data' => $questao,
            'add' => false,
                ), true) . '</li>';
    }
    ?>
</ul>
<hr>
<h4>Outras questões disponíveis.</h4>
<?php echo CHtml::textField("filtroTopicos", "", array('placeholder' => 'Localizar questão...', 'id' => 's', 'class' => 'form-control column medium-4')); ?>
<br><br>

<ul class="medium-block-grid-4 small-block-grid-1">
    <?php
    foreach ($questoes as $questao) {
        if (!in_array($questao->id, $noQuestionario)) {
            echo '<li>' . $this->renderPartial('_questao', array(
                'id' => $questionario->id,
                'data' => $questao,
                'add' => true,
                    ), true) . '</li>';
        }
    }
    ?>
</ul>
<script>
    $('#s').keyup(function() {
        $('.s').each(function() {
            var n = $(this).text().toLowerCase();
            if (n.indexOf($('#s').val().toLowerCase()) === -1) {
                $(this).parent().parent().fadeOut();
            } else {
                $(this).parent().parent().fadeIn();
            }
        });
    });
</script>

shared/modules/questionarios/views/questionario/imprimir.php
<h1><?= $questionario->nome; ?></h1>
<?php
foreach ($questionario->questoes as $questao) {
    echo '<h4>' . $questao->titulo . '</h4>';
    if ($questao->tipo == QstQuestao::CincoAlternativas) {
        $this->renderPartial('/questao/_verCincoAlternativas', array('questao' => $questao));
    } elseif($questao->tipo == QstQuestao::VerdadeiroOuFalseo){
        $this->renderPartial('/questao/_verVerdadeiroOuFalso', array('questao' => $questao));
    }
}

shared/modules/questionarios/views/questionario/listar.php
<?php
$this->pageTitle = 'Questionários';
$this->menuContexto = array(
    ShCode::makeItem('Novo questionário', $this->createUrl('questionario/novo')),
);
?>
<div class="sh-row">
    <div class="column medium-12">
        <ul class="nav">
            <?php foreach ($questionarios as $q): ?>
                <li><?= CHtml::link($q->nome, $this->createUrl('questionario/editar', array('id' => $q->id))) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

shared/modules/questionarios/views/questionario/novo.php
<?php
$this->pageTitle = 'Novo questionário';
$this->menuContexto = array(
    ShCode::makeItem('Cancelar', $this->createUrl('questionario/listar')),
);
?>
<div class="sh-row">
    <div class="columns medium-12">
        <p class="hint">
            Configurações de tempo de resolução, quantidade de tentativas, etc, 
            serão definidas no quando o questionário for utilizado.
            <br>
            <br>
        </p>
        <?php $this->renderPartial('_form', array('model' => $model)); ?>
    </div>
</div>